export const SECRET_KEY =
	'aribirdisthefirstcryptoarcadegamewhereyougetdailyrewardsbywinningastopscorer'
export const AUTH =
	'U2FsdGVkX18RxeyIRwbvoLbqWMVGLRhVmHdExqL1xUE=U2FsdGVkX1/VVroGGay2AfWBODbKoymEvzeY9FJ2mB4='
